conf_forward:
  options_ghc:
    - -XLambdaCase
    - -XMultiWayIf
    - -XGADTs
    - -XPatternGuards
    - -XViewPatterns
    - -XRecursiveDo
    - -XTupleSections
    - -XExplicitForAll
    - -XImplicitParams
    - -XQuasiQuotes
    - -XTemplateHaskell
    - -XBangPatterns
    - -XRecordWildCards
    - -XTypeApplications
    - -XOverloadedLabels
    - -XRankNTypes
conf_obfuscate: false
conf_layout:
  lconfig_cols: 120
  lconfig_indentPolicy: IndentPolicyMultiple
